jwt.secret.key: c3BhcnRhd2VlazJob21ld29ya2p3dGp3dGp3dHNlY3JldHNlY3JldGtleWtleXNwYXJ0YXdlZWsyaG9tZXdvcms=

---
spring:
  config:
    activate:
      on-profile: "common-local" # 로컬 환경일 때 적용

logging.level:
  org.apache.coyote.http11: debug # 콘솔에 http 요청을 로그로 보여줄 수 있는 설정
---
spring:
  config:
    activate:
      on-profile: "common-dev" # dev 환경일 때 적용

logging.level:
  org.apache.coyote.http11: debug